version: '3.9'

services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80

  mysql_database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: docker_php
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1